path: /data/huxingjian/workspace/sam2/data/OBIMD_raw_hj/yolo/ # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/test # val images (relative to 'path') 4 images

nc: 1 # number of classes

names:
  0: OBC